name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_draft:
    name: Create Draft
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Release Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2

      - name: Install tera
        run: |
          URL=https://github.com/chevdor/tera-cli/releases/download/v0.2.0/tera-cli_linux_amd64.deb
          wget $URL
          sudo dpkg -i tera-cli_linux_amd64.deb
          tera --version

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.0.2"

      - name: Install changelogerator
        run: |
          gem install pry
          gem install changelogerator --with=dev
          changelogerator --help

      - name: Generate changelog
        id: change_log
        run: |
          export REF1=$(git describe --tags --abbrev=0 ${{ env.RELEASE_VERSION }}^ )
          export REF2=${{ env.RELEASE_VERSION }}
          export REPO=$GITHUB_REPOSITORY

          CL_FILE=cl_data.json
          echo Using CL_FILE: $CL_FILE
          echo Building changelog for $REPO between $REF1 and $REF2
          export RUST_LOG=debug;

          changelogerator $REPO -f $REF1 -t $REF2 > $CL_FILE

          cp templates/template.md templates/dyn.md
          echo "" >> templates/dyn.md
          for f in $(git diff --name-only $REF1..$REF2 doc); do
            file=$(basename $f)
            echo "{% include \"prs/$file\" %}" >> templates/dyn.md
          done

          jq \
            --slurpfile cl $CL_FILE \
            -n '{ cl: $cl[0] }' | tee context.json

          tera --env --env-key env --include-path doc/ --template templates/dyn.md context.json | tee changelog.md

          cat changelog.md

      - name: Save Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: |
            changelog.md
